# Generated by Django 4.2 on 2023-04-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EBS2021", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=100)),
                ("request", models.CharField(max_length=150)),
                ("response", models.CharField(max_length=150)),
                ("responsecode", models.CharField(max_length=5)),
                ("transactionDate", models.DateTimeField()),
                ("uuid", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="UserPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userName", models.CharField(max_length=100)),
                ("cardHolder", models.CharField(max_length=100)),
                ("cardNumber", models.CharField(max_length=15)),
                ("expiryDate", models.DateField()),
                ("transactionId", models.CharField(max_length=20)),
                ("transactionDate", models.DateTimeField()),
                ("transactionAmt", models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name="booking",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="sponsortbl",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="usersignup",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
